version: ‘3’
services:
  db:
    image: 'postgres:15.5-alpine'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWD}'
      POSTGRES_USER: postgres
